version: '1.0'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbit-mq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  parser:
      build: .
      container_name: my-parser
      ports:
      - 9000:9000
      depends_on:
        - rabbitmq
        - elasticsearch
        - kibana


  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - discovery.type=single-node
      - node.name=es01
      - bootstrap.memory_lock=true
    networks:
      - elastic
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


  kibana:
      container_name: kb-container
      image: docker.elastic.co/kibana/kibana:7.11.0
      networks:
        - elastic
      depends_on:
        - elasticsearch
      ports:
        - 5601:5601

volumes:
 esdata:

networks:
  elastic: